version: '3'

services:

  server:
    build: .
    volumes:
      - ./:/go/src/app
    ports:
      - "8080:8080"

  db:
    image: postgres:14-alpine
    volumes:
     - dbdata:/var/lib/postgresql/data
    env_file:
     - .env
    ports:
      - "5432:5432"

volumes:
  dbdata:
    name: volume

